# Choose Your Own Adventure
# Layla ibrahim
# 24 September
#
# Choose your own adventure story focusing
# on using variables and branching/conditionals
#
# Introducting

import time

# Print the text of the story.
print("You're a junior at Ridgewood High — a school that's old enough to have legends and weird rumors about hidden rooms, secret societies, and haunted wings.")
time.sleep(1.5)
print("The hallway smells like dust and time. The lights flicker. At the end of the corridor, you find a heavy wooden door with no handle, but a strange symbol carved into it.")
time.sleep(1.5)
print("Suddenly, your phone buzzes.It's a message from an unknown number:")
time.sleep(1.5)
print("Don’t open it. You’re not ready.")
time.sleep(4)
print("You look back. The hallway behind you is pitch black.")
print("What do you do?")
time.sleep(1)
print("A) Try to open the mysterious door.")
print("B) Text back the unknown number.")
print("C) Go back down the hallway and try to leave.")

# Ask the user for their choice.
choice = input("Your choice: ")

if choice == "a":
    print("You place your hand on the symbol. The door makes a click, then swings open silently. A dim room lies beyond, filled with books, strange tools, and a glowing orb on a pedestal. As you step inside, the door closes behind you.")
    print("You hear a voice — not in your ears, but in your head:")
    print("“You’ve found the Arcane Room. Will you take the power?”")
    print("In front of you now are two items:")
    time.sleep(1)
    print("A leather-bound book with your name on the cover")
    print("A floating key that pulses with energy")
    print(" What do you do?")
    time.sleep(1)
    print("A) Take the book.")
    print("B) Take the key.")
    print("C) Refuse both and try to leave.")
elif choice == "b":
    print("Text back the unknown number")
    print("Who is this?")
    time.sleep(1)
    print("Someone who used to be in your place. Get out of that hallway NOW.” ")
    time.sleep(1)
    print("A distant sound echoes — footsteps, heavy ones, even though you saw no one earlier.")
    print("Your phone buzzes again:")
    time.sleep(1)
    print("If you want answers, meet me under the bleachers after school. But don’t go through that door.")
    print("The air grows colder.You glance at the door again. It seems to call to you.")
    print("What do you do?")
    time.sleep(2.5)
    print("A) Leave the hallway and go to the meeting.")
    print("B) Open the door anyway")
    print("C) Stay where you are and wait")
    if choice == "a"
    print("You listen to the warning and leave the hallway.")
    print("After school, you meet the mysterious person under the bleachers — they’re older, clearly shaken, and claim they were once in your exact position.")
    print("They reveal that the door is a trap — something not human lures people in, promising power but feeding on them instead.")
    print("By trusting the warning, you’ve taken the first step into a hidden resistance — people trying to shut the door for good.")
    print("This path leads to:Discovery, secret societies, and becoming part of the fight against the entity behind the door.")
    if choice "b"
    print("Curiosity wins. You open the door.")
    print("Inside, you find a staircase leading to a dark, high-tech chamber — with surveillance equipment and a strange chair wired to the ceiling.")
    print("You realize too late: they were expecting you.")
    print("The door seals behind you. A voice speaks:")
    time.sleep(3)
    print("So. You chose curiosity.")
    time.sleep(3)
    print("You’ve been caught by something — or someone — studying those who ignore the warning.")
    print("This path leads to:⚠️Captivity, experiments, and potentially uncovering the true purpose of the door… from the inside.")
    if choice "c"
    print("You don’t move. You resist the pull of the door and the warning.")
    time.sleep(1)
    print("After a tense few moments, someone arrives — the person who sent the message.")
    print("They see you waited, and that earns their trust.")
    print("They tell you that your choice proved you could resist the door’s influence.")
    print("They’ve been monitoring the phenomenon — and you might be key to stopping it, not just escaping it.")
    print("This path leads to: Trust-building, answers, and possibly a mentor guiding you into something much bigger.")
    if choice "a"
    print("You follow the warning and meet the mysterious figure under the bleachers. They're quiet at first, watching you carefully, like they weren’t sure you’d show.")
    time.sleep(2)
    print("Then they speak.")
    time.sleep(3)
    print("You passed the test. Most people don’t. They open the door, and they’re never the same.")
    print("They hand you an old photograph — a group of students standing in front of the very door you found. Most of their faces are scratched out.")
    print("We were trying to stop it. We failed.")
    print("You become part of something bigger — a hidden network trying to destroy the entity behind the door. You learn symbols of protection, how to listen for when the door is active… and how to close it when it opens.")
    print("You never go near that hallway again.")
    print("But sometimes, you feel it watching.")
    print("Ending: You chose wisdom over curiosity. You survived… and now you guard others.")
    if choice "b"
    print("You open the door. You couldn’t help it.")
    print("The chamber below hums with energy. Screens flicker to life with footage of you — your room, your school, your dreams. They’ve been watching for a long time.")
    print("A chair waits in the center of the room. The restraints open automatically, inviting you to sit.")
    print("When you try to run, the door seals behind you.")
    print("A voice, calm and cold, crackles through a speaker.")
    print("Curiosity is the key. And now, you’re ours.")
    print("Your memories begin to slip. The world outside fades. You are studied, shaped, and perhaps one day, used to lure the next curious soul.")
    time.sleep(3)
    print("Ending: You chose knowledge over caution. And now, you're part of the experiment.")
    if choice "c"
    print("You wait.")
    time.sleep(2)
    print("The door pulses behind you, but you stand still. Minutes pass. The hallway grows colder — then warmer. Then quiet.")
    time.sleep(3)
    print("Finally, someone appears. They look normal. But their eyes tell a different story — like they’ve seen the other side.")
    print("I was you, once.")
    print("They hand you a small object: a black coin etched with a symbol — the same one from the door. It’s warm in your hand.")
    time.sleep(2)
    print("You didn’t open it. That matters. The door feeds on choice. You made the right one.")
    print("You're told the truth — the door isn’t just a portal. It’s alive. It chooses people. It tempts them.")
    print("But now, it fears you.")
    time.sleep(1)
    print("You’ve earned something more than power — a resistance to it.")
    print("And the coin?")
    time.sleep(2)
    print("You’ll need it soon.")
    time.sleep(2)
    print("Ending: You chose patience. You were chosen in return.")
